[자동차 경주] 이유빈 미션 제출합니다.
poi1649/java-racingcar-6 pull request #1
Opened 2024-01-24 07:04 UTC by leeshin20

2024-01-26 07:21 UTC, poi1649 requested changes
첫 미션 고생많으셨습니다.
생각하신 것 이상으로 꼼꼼하고, 컨벤션도 거의 다 지켜주셔서 보기 좋은 코드였습니다.
커밋 단위도 잘 나눠주셔서 리뷰가 훨신 편했어요.
다만 미션의 요구사항에서 어긋난 부분이 아주 조금 있는 것 같아. 몇 가지 커멘트 남겼어요! 확인하시고 월요일 6시까지 리뷰 반영후 다시 풀리퀘스트 주시면 감사하겠습니다.
(같은 브랜치에 그대로 push하면 커밋 사항이 그대로 반영되니 수정후 push 해주시면 됩니다).
또 커멘트에 의견도 남겨주시면 좋아요! 화이팅입니다~ 혹시 일정이 촉박하면 이틀전에 말씀주세요!

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/Application.java
> +}
파일의 마지막줄엔 개행이 필요하고, 만약 개행이 없으면 깃허브, IDE 등에서 경고가 발생합니다. 왜 그럴까요!?
<img width="121" alt="스크린샷 2024-01-13 오후 12 26 08" src="https://github.com/woowacourse-precourse/java-lotto-6/assets/74969077/cd90cfe5-cf84-4107-ad47-c45590dc5be7">

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/Car.java
> +    private static final int FORWARD_CONSTANT = 4;
[구글 스타일](https://google.github.io/styleguide/javaguide.html#s3.4.2-ordering-class-contents)에서는 명확한 규칙을 제시하지는 않지만, 클래스 멤버 변수들, 메서드들의 선언도 논리적 규칙을 가져야 합니다.
팀에서 협업을 하게되면 팀의 규칙을 따르겠지만, 혼자 코딩을 한다면 스스로 규칙을 정해야합니다.
저는 [오라클 컨벤션](https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html) 을 주로 참고하는데, 한 번 생각해보세요😎

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/Car.java
> +    }
이 프로그램의 핵심 로직인 것 같아요.
이 메서드의 테스트는 어떻게 할 수 있을까요!?

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/RacingGameManager.java
> +            car.forward();
forward는 동사로 쓰일 때 전달하다 라는 뜻으로 주로 쓰이지 않나요?
의도하신 대로 표현하려면 move나 moveForward 등이 적절해보입니다.

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/RacingGameManager.java
> +    public static void startRace() {
[구글 스타일 가이드](https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace) 에 따르면 필드와 메서드 사이엔 세로 공백이 필요해요!👍

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/RacingGameManager.java
> +        Output.inputNameMessage();
메서드 이름은 동사형으로 짓습니다!!!!

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/Output.java
> +public class Output {
1. Input과 Output 클래스의 메서드들을 스태틱으로 선언해 사용하시는 이유가 있으실까요!?
2. 인스턴스 메서드와 스태틱 메서드의 차이는 뭘까요?
3. 스태틱 메서드만을 가지는 유틸성 클래스에서는 보통 오사용을 방지하기 위해 기본 생성자를 private으로 선언합니다!

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/Output.java
> +        for(int i=0; i<number; i++){
공백도 컨벤션입니다! IDE를 어떤 걸 사용하시는지 모르겠지만, 자동정렬 기능을 습관적으로 사용하시는 것이 좋습니다.
(인텔리제이는 cmd + l) 로 자동정렬이 가능합니다. [제 블로그](https://velog.io/@bjk1649/%EC%9A%B0%EC%95%84%ED%95%9C-%ED%94%84%EB%A6%AC%EC%BD%94%EC%8A%A4-1%EC%A3%BC%EC%B0%A8-%ED%9B%84%EA%B8%B0) 참고하셔서 스타일 가이드 IDE에 등록해놓으시는 것도 추천드려요~

2024-01-26 07:21 UTC, poi1649 commented on src/test/java/racingcar/InputTest.java
> +    void 자동차_이름_분할_테스트() {
오 한글로된 메서드 이름을 사용하셨네요. 이유가 있으실까요!?

2024-01-26 07:21 UTC, poi1649 commented on src/test/java/racingcar/RacingTest.java
> +    }
어떤 차가 정확히 우승하는지 테스트를 할 방법은 없을까요~

2024-01-26 07:21 UTC, poi1649 commented on src/test/java/racingcar/InputTest.java
> +    }
오... 테스트 코드의 이런저런 메서드들 잘 학습하셨네요 너무 훌륭합니다 💯💯💯💯
경계값으로 테스트해주신 것도 좋네요.

그런데 몇가지 의문이 생긴 부분도 있어서 질문드려요
1. 에러 메시지까지 검증했을 때 어떤 장점과 단점이 있을까요?
2. 시도할 횟수 예외처리 메시지를 봤을 때 0이나 -1 같은 숫자를 입력할 것 같은 느낌을 받았는데 문자열을 테스트하고 있어요. 다른 예외메시지가 더 적당할 수도 있지 않을까요?

2024-01-26 07:21 UTC, poi1649 commented on src/main/java/racingcar/Output.java
> +                System.out.print(", ");
ㅋㅋㅋㅋㅋ 아주 신박한 방법이네요. 물론 이런식으로도 해결할 수 있지만, 자바 내장 라이브러리에서 제공하는 기능을 이용해보시면 코드가 더 깔끔해질게요.
String.join 메서드에 대해 찾아보시죠!

2024-01-26 07:21 UTC, poi1649 commented on docs/README.md
> +    - 우승자가 2명 이상인 경우, 2번째 우승자 부터 `", {자동차 이름}"`을 출력
꼼꼼한 요구사항 정리는 모든 프로그래밍의 기본입니다. 너무 훌륭하네요💯💯
요구사항을 작성하며 어떤 이점을 느끼셨나요!?

2024-01-29 06:34 UTC, leeshin20 commented on src/main/java/racingcar/Car.java
> +    private static final int FORWARD_CONSTANT = 4;
해당 커멘트 참고하여 몇 가지 변수와, 메서드를 수정했습니다

- - -

**Car**
_FORWARD_CONSTANT_ -> 삭제
_raceScore_ -> _moveDistance_
_forward()_ -> _move()_
_getRaceScore()_ -> _getMoveDistance()_

_forward_ 메서드는 작성해주신 커멘트를 참고하여 _move_로 이름을 수정했습니다.

_raceScore_ 변수는 _move_ 메서드와 연관성을 알기 쉽게 하고자, _moveDistance_ 로 이름을 수정했습니다.

변수 이름에 맞춰 _getRaceScore_ 메서드를 _getMoveDistance_ 로 이름을 수정했습니다.

_FORWARD_CONSTANT_ 의 경우, 해당 상수가 _move_ 메서드에서 단 한번만 사용되는 점,
그리고 _move_ 메서드의 기능이 간단하여 굳이 상수로 선언하여 사용하지 않아도 가독성에 문제가 없을 것이라 판단 되어 삭제했습니다.

- - -

**RacingGameManager**
carEntry() -> entryCar()

달아주신 커멘트를 참고하여 동사가 앞으로 오도록 수정했습니다.

- - -

**Output**
_printResult_ -> _result_
_printProgress_ -> _progress_
_printWinner_ -> _winner_

해당 메서드를 다른 클래스에서 사용하면 _Output.printResult_ 같은 식으로 Output과 print 유사한 의미를 가진 단어가 두 번 사용되기 때문에 메서드 이름에 굳이 print가 없어도 되지 않을까 하는 생각이 들었습니다.

이 부분에 대해서 어떻게 생각하시는지 궁금합니다!

2024-01-29 06:59 UTC, leeshin20 commented on src/main/java/racingcar/Application.java
> +}
IEEE에서 이식성이 높은 UNIX 응용 프로그램을 개발하기 위한 목적으로 책정한 인터페이스 규격인 POSIX에 따르면
```
[3.206 Line]
A sequence of zero or more non- <newline> characters plus a terminating <newline> character.
[3.195 Incomplete Line]
A sequence of one or more non- <newline> characters at the end of the file.
```
줄 바꿈이 하나의 행을 정의하는 기준이 되기 때문에, 파일 끝에 newline 문자가 없으면 끝나지 않은 행으로 간주됩니다.

C의 컴파일러인 gcc의 경우 해당 규격을 따라, 파일의 마지막에 개행문자가 없다면 한 줄이 끝나지 않은 것으로 인식해서 정상적으로 동작하지 않는 문제가 발생할 수 있습니다.

따라서 이 같은 오류를 예방하기 위해 Github, IDE에서는 파일 끝에 개행이 없을 시 경고를 발생시킵니다.

2024-01-29 07:04 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +            car.forward();
동사의 의미를 생각하여 선언하겠습니다!

2024-01-29 07:13 UTC, leeshin20 commented on src/main/java/racingcar/Car.java
> +    }
```
@Test
    void carMoveTest() {
        Car testCar = new Car("test");
        while (testCar.getMoveDistance() < 1) {
            testCar.move();
        }
        assertThat(testCar.getMoveDistance()).isGreaterThan(0);
    }
```

테스트를 위한 testCar 인스턴스를 생성하고
while문으로 testCar.move() 메서드를 실행하여 전진하는 결과가 발생할 때 까지 반복합니다.
최종적으로 testCar.move()가 제대로 실행되어 moveDistance가 상승 하였는지 판단하는 테스트 코드를 추가했습니다!

2024-01-29 07:14 UTC, leeshin20 commented on src/main/java/racingcar/Output.java
> +        for(int i=0; i<number; i++){
저장과 자동정렬 습관처럼 누르겠습니다!

2024-01-29 07:16 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +    public static void startRace() {
주의하겠습니다!

2024-01-29 07:16 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +        Output.inputNameMessage();
_carEntry()_ -> _entryCar()_ 로 수정하였습니다
감사합니다!

2024-01-29 07:34 UTC, leeshin20 commented on src/test/java/racingcar/InputTest.java
> +    }
<img width="503" alt="스크린샷 2024-01-29 오후 4 19 58" src="https://github.com/poi1649/java-racingcar-6/assets/28841458/6646c830-76fc-49fb-a45e-5095d1833b6c">

1. 장점 : 테스트 진행 시, 위의 스크린샷 처럼 어느 구간에서 테스트가 실패했는지 명확하게 파악할 수 있습니다.
단점 : 개발자가 예상하지 못 한 에러 메시지가 발생할 경우 테스트가 실패할 수 있으며, 에러 메시지를 검증하는 기능을 추가하면 코드가 길어져 가독성이 떨어질 수도 있습니다.

2. 실수로 숫자가 아닌 문자를 입력하는 경우를 생각하고 예외메시지를 작성하였는데, 확실히 보통 숫자를 입력하는 부분이다 보니까
`0 or -1`을 입력하는 메시지를 넣거나, `0 or -1`과 `{숫자가 아닌 문자}` 두 가지 메시지에 대해서 모두 테스트를 진행하는 식으로 작성을 하는게 좋았을거란 생각이 듭니다!

2024-01-29 07:36 UTC, leeshin20 commented on src/main/java/racingcar/Output.java
> +                System.out.print(", ");
```
System.out.println(String.join(", ", names));
```

String.join 메서드를 사용하니 정말 간단하게 구현이 되었습니다!
자바 내장 라이브러리도 알아두면 도움이 많이 될 것 같습니다!
감사합니다!!!

2024-01-29 07:41 UTC, leeshin20 commented on src/test/java/racingcar/RacingTest.java
> +    }
```
@Test
    void 우승자_선정_결과_테스트() {
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("test1"));
        cars.add(new Car("test2"));
        cars.add(new Car("test3"));
        while (cars.get(0).getMoveDistance() < 1) {
            cars.get(0).move();
        }
        while (cars.get(1).getMoveDistance() < 1) {
            cars.get(1).move();
        }
        ArrayList<String> winners = RacingGameManager.findWinner(cars);
        assertThat(winners).containsExactly("test1", "test2");
    }
}
```

test1, test2, test3 인스턴스를 생성하고,
test1, test2 두 자동차만 1칸 전진하도록 합니다
```
test1 : -
test2 : -
test3 : 
```
다음으로 _RacingGameManager.findWinner(cars)_ 메서드로 우승자를 판별합니다
이 때 반환 된 우승자가 test1, test2로 정확히 일치할 때 테스트가 성공하도록 수정했습니다

2024-01-29 07:45 UTC, leeshin20 commented on src/test/java/racingcar/InputTest.java
> +    void 자동차_이름_분할_테스트() {
프로젝트를 불러왔을 때 있던 ApplicationTest와 StringTest 파일의 테스트 메서드의 이름이 한글로 작성되어 있었기 때문에 그대로 한글로 작성을 했습니다!

테스트 메서드의 경우도 기존의 컨벤션 가이드 규칙을 지켜서 영어로 작성하면 될까요?

2024-01-29 07:56 UTC, leeshin20 commented on docs/README.md
> +    - 우승자가 2명 이상인 경우, 2번째 우승자 부터 `", {자동차 이름}"`을 출력
어렴풋이 자동차 경주의 큰 그림을 생각할 때는 딱히 생각이 막히는 부분이 없었습니다.
그런데 막상 구현할 기능을 하나씩 꼼꼼하게 작성 하려니 지금 적은 부분에 문제는 없는지, 혹시 빠트린 것은 없는지 곰곰히 검토하게 되어 생각보다 시간이 더 걸렸습니다.

그렇게 문서에 정리를 하니까, 하나의 기능을 구현하고 그 다음에 어떤 것을 구현해야 되는지 고민할 필요 없이 정리된 문서를 통해 확인할 수 있어서 빠르게 진행이 가능했고, 누락된 기능에 대한 파악도 훨씬 빠르게 가능했습니다.

만약 요구사항을 생각하고 정리하는 과정없이 바로 코드를 작성하기 시작했다면, 분명 여기저기 기능에 누락이 생기고, 고민했던 내용을 또 고민하는 등 시간 낭비가 많았을거라 생각이 됩니다. 실제로 알고리즘 문제를 풀 때, 이런 경험이 있었기 때문에 내용을 정리했을 때의 이점이 잘 와닿았던 것 같습니다!

2024-01-29 08:05 UTC, leeshin20 commented on src/main/java/racingcar/Output.java
> +public class Output {
1. 다른 클래스에서 Input, Output 클래스의 메서드를 사용할 때, 인스턴스를 새로 만들지 않아도 메서드를 사용할 수 
있도록 하기 위해 static으로 선언했습니다!
2. 스태틱 메서드는 클래스의 인스턴스 생성 없이 `{클래스이름.method()}`와 같은 식으로 호출할 수 있지만,
  인스턴스 메서드는 해당 메서드를 사용하려는 클래스에서 인스턴스를생성한 후,  `{객체이름.method()}`와 같은 식으로 호출해야 사용할 수 있습니다!

3. private 기본 생성자를 새로 선언했습니다!

감사합니다!

2024-01-30 12:26 UTC, Cyma-s commented on src/main/java/racingcar/Application.java
> +}
맞아요. 이런 개행을 저희가 일일이 신경 쓰는 건 굉장히 귀찮기 때문에, IDE 설정을 해두시면 편합니다!
사진 맨 아래에 '모든 저장된 파일이 줄 바꿈으로 끝나도록 함'을 체크해주시면 자동으로 설정된답니다 👍🏻 

<img width="903" alt="image" src="https://github.com/poi1649/java-racingcar-6/assets/61370551/3ef75479-6a57-4278-9662-e25563ba669f">

2024-01-30 13:25 UTC, Cyma-s commented on src/main/java/racingcar/Car.java
> +    private static final int FORWARD_CONSTANT = 4;
수정해주신 변수와 메서드와 관련해서 말씀드리고 싶은 부분이 몇 가지 있어 댓글 남깁니다 :)

1. 변수는 명사로, 메서드는 동사로 시작하도록 작명하기
현재 바꿔주신 변수 이름이 `moveDistance` 인데, 해당 변수 이름은 동사로 시작하고 있습니다. 또한 말씀해주신 Output 의 result, progress, winner 는 명사입니다. 변수와 메서드는 각각 명사로 시작하도록 네이밍하는 것이 컨벤션이기 때문에, 이런 컨벤션들을 잘 지켜주시면 다른 개발자가 코드를 좀 더 명확하게 읽는 데 도움이 됩니다 ☺️

2. 매직 넘버는 상수로 추출하기
만약 유빈님의 코드를 처음 읽는 개발자가 있다면, 해당 숫자가 왜 이 값인지, 어떤 의미를 갖는지 숫자 자체로는 이해할 수 없을 거에요. 그리고 동일한 값을 사용하는 코드가 추후에 생기게 된다면, 이 값과 다른 값의 연관성을 숫자 자체로는 표현할 수 없다는 단점이 있어요. 그렇기 때문에 매직 넘버는 상수로 선언해주는 것이 좋습니다 :) 
추가로 상수의 이름은 해당 상수를 읽는 사람이 이해하기 쉽게 `CONSTANT` 와 같은 일반적인 단어보다 의미가 담겨 있는 구체적인 이름으로 작명해주는 것이 좋습니다!

앞으로도 개발을 하다보면 이 단어를 영어로 어떻게 표현해야 하는지 헷갈릴 때가 많은데요, 그럴 땐 영어 사전을 함께 보면서 네이밍하는 것도 도움이 많이 됩니다 👍🏻 저도 영어가 약한 편이라 사전 보면서 개발하고 있어요 ㅎㅎ

2024-01-30 13:29 UTC, Cyma-s commented on src/main/java/racingcar/Car.java
> +    }
굉장히 창의적인 방식이군요 ㅋㅋㅋ 👍🏻 
1. 여러 개의 Car 가 움직이는 것을 테스트하려면 어떻게 해야 할까요? 그때도 지금과 같은 방식으로 테스트할 수 있을까요?
2. 만약 정말 운이 안 좋아서, 계속해서 차가 움직이지 않는 경우에는 해당 테스트는 어떻게 될까요?

2024-01-30 13:31 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +        Output.inputNameMessage();
차를 등록하는 과정을 메서드로 만들고 싶으셨다면 `registerCar` 같은 네이밍이 조금 더 적합해보입니다 :)

2024-01-30 13:34 UTC, Cyma-s commented on src/main/java/racingcar/Output.java
> +public class Output {
현재 `Input` 과 `Output` 클래스가 인스턴스화 되지 않고 메서드를 제공하기만 하는 유틸성 클래스로서의 역할을 하고 있는데, `Input` 과 `Output` 인스턴스를 만들어서 사용하는 것과 외부에서 static 메서드들을 호출할 수 있도록 하는 유틸성 클래스로서 사용하는 것은 어떤 차이점이 있을까요?

2024-01-30 13:38 UTC, Cyma-s commented on src/test/java/racingcar/InputTest.java
> +    void 자동차_이름_분할_테스트() {
테스트 메서드의 이름은 팀마다 다르지만, 한글로 쓰기도 하고 영어로 쓰기도 합니다.  
테스트 메서드의 이름을 한글로 작성했을 때는 해당 메서드가 어떤 것을 테스트하는지 알아보기 쉽습니다. 다만 메서드 이름을 한글로 작성하면 IDE 에서 경고가 발생하기 때문에 추가로 설정을 해주어야 합니다.
영어로 작성하는 경우는 추가로 설정을 해줘야 할 필요가 없고, 한글을 모르는 외국인들도 테스트 메서드를 알아볼 수 있다는 장점이 있지만, 이름이 한글로 작성된 메서드보다는 해당 메서드가 어떤 역할을 하는지 알아보는 데 시간이 더 걸린다는 단점이 있습니다.  

유빈님이 생각하시기에 더 괜찮은 방법을 선택하시면 됩니다 :)

2024-01-30 13:39 UTC, Cyma-s commented on src/test/java/racingcar/RacingTest.java
> +    }
위에 남겼던 커멘트와 마찬가지로, Car 의 개수가 더 많이 늘어났을 때도 이렇게 테스트를 할 수 있을까요?!

2024-01-30 13:42 UTC, Cyma-s commented on src/test/java/racingcar/InputTest.java
> +    }
좋습니다 👍🏻 예외 메시지까지 검증했을 때는 추후 예외 처리 메시지가 변경될 때마다 테스트 메서드를 수정해주어야 한다는 번거로움이 있다는 점도 참고해주시면 좋을 것 같아요 😄

2024-01-30 14:11 UTC, Cyma-s requested changes
안녕하세요 유빈님! 이번 리뷰부터 코드리뷰를 맡게 된 김은솔입니다 :) 반갑습니다!
작성해주신 댓글과 변경된 코드 위주로 리뷰를 남겨보았습니다 😄
궁금하신 점이나 어려운 점, 이해가 안 되는 부분은 언제든 댓글로 알려주세요! 모든 질문을 환영합니다 :)
리뷰 반영 파이팅입니다 🔥

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +        ArrayList<String> nameList = new ArrayList<>(Arrays.asList(names.split(",")));
변수의 이름에는 타입이 들어가지 않는 것이 좋습니다! 추후 해당 변수의 타입이 바뀌게 된다면 변수의 이름도 함께 바꿔야 하기 때문에 관리 지점이 늘어난다는 단점이 있어요!

아래는 질문입니다. 생각해보시고 답변 남겨주세요 😄

1. 변수를 선언할 때 `List` 타입으로 선언하는 것과 `ArrayList` 타입으로 선언하는 것은 어떤 차이점이 있고 어떤 것을 선택하는 것이 좋을까요?
2. 메서드의 리턴 타입을 선언할 때 `List` 타입으로 선언하는 것과 `ArrayList` 타입으로 선언하는 것은 어떤 차이점이 있고 어떤 것을 선택하는 것이 좋을까요?
3. `ArrayList` 는 불변리스트가 아니기 때문에, 리턴된 리스트에는 데이터의 삽입, 삭제, 변경이 일어날 수 있습니다. 리턴된 리스트에 변경이 일어날 수 있다면 어떤 일이 발생할까요?

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +            if (name.length() > 5) {
만약 여기에 있는 5를 상수 처리하게 된다면 어떤 장점이 있을까요?

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +    public static int inputNumber() {
해당 메서드를 사용하게 된다면 `Input.inputNumber()` 와 같은 방식으로 사용하게 될 것 같아요! 그런데 `inputNumber` 라는 메서드는 마치 개발자가 해당 메서드에 인자를 넘겨야 할 것 같은 느낌을 줍니다. 
아래의 `Console.readLine()` 을 보시면, 'Console 이 Line 을 읽는다' 라고 읽히죠. 이렇듯 다른 개발자에게 혼란을 주지 않으려면 메서드가 호출되었을 때, 개발자가 잘 이해할 수 있는 네이밍을 짓는 것이 굉장히 중요합니다 👍🏻 
조금 더 적합한 네이밍은 없을까요?!

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +        if (!isNumber(number) || Integer.parseInt(number) <= 0) {
하나의 예외로 묶는 것도 좋지만, 각 경우에 따라 예외를 세분화한다면 조금 더 명확한 예외처리를 할 수 있을 것 같네요 😄

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      private static int raceCount;
모든 필드를 static 필드로 선언하신 이유가 있을까요? static 필드와 인스턴스 필드의 차이점은 뭘까요?

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      private static final ArrayList<Car> cars = new ArrayList<>();
`ArrayList` 를 final 로 선언해주셨네요 👍🏻 final 로 선언한 변수는 어떤 특징을 갖게 되나요?

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      public static void startRace() {
`RacingGameManager` 에 있는 모든 메서드를 static 으로 선언해주셨는데, 이유가 있을까요?

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +            if (car.getMoveDistance() == highScore) {
이 부분은 차가 움직인 거리가 highScore 와 같은지 확인하는 조건문이네요!
즉, 해당 차가 winner 인지 아닌지 판단하는 역할을 하고 있어요. 
이런 경우, 단순하게 `moveDistance` 를 getter 로 가져와서 highScore 와 비교하기보다, Car 의 메서드로 넣어서 '의미를 부여해주는 것'이 좋습니다 :) 
다음과 같이 써볼 수 있을 것 같아요!

```suggestion
            if (car.isWinner(highScore)) {
```

2024-01-30 14:11 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      }
여기에서 리턴해주는 값은 static 필드 `cars` 인데, 위에서 리턴한 값을 '지역 변수' `cars` 에 넣고 있어요. 이 경우, Output.result 에서 출력하는 값은 필드의 값이 아닌 지역 변수의 값이라는 뜻입니다. 현재는 무리 없이 잘 실행되고 있지만, 추가적인 로직이 생길 경우 유빈님이 의도하신 것과 다르게 행동할 가능성이 매우매우 높습니다.
그리고 처음에 `cars` 를 final 로 선언하셨기 때문에 `cars` 에 재할당을 할 수 없는 상태입니다. 즉, `cars = runRaceOneTime()` 처럼 재할당을 할 수는 없습니다. 

그렇다면 이 부분을 어떻게 고쳐볼 수 있을까요? 힌트를 드리자면 현재 구조에서도 `cars` 를 리턴하지 않아도 무방합니다 :)

2024-02-01 03:54 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
> +        ArrayList<String> nameList = new ArrayList<>(Arrays.asList(names.split(",")));
> 1. 변수를 선언할 때 List 타입으로 선언하는 것과 ArrayList 타입으로 선언하는 것은 어떤 차이점이 있고 어떤 것을 선택하는 것이 좋을까요?

변수를 각각 `List`타입,  `ArrayList` 타입으로 선언하는 것의 차이는
`List`타입으로 선언 된 변수는 어떤 종류의 리스트가 사용되는지의 여부와 관계없이 `ArrayList`나 `LinkedList` 등 다른 리스트로 구현할 때도 변수의 선언 타입을 고치지 않고 바로 구현할 수 있습니다.
반면, `ArrayList`타입으로 선언 된 경우, 항상 `ArrayList` 객체만 참조하여 사용되기 때문에 `List` 타입을 사용하는 것에 비해 유연성이 떨어집니다.
따라서, `ArrayList`가 아닌 `List` 타입을 사용하는 것이 더 좋다고 생각됩니다.


> 2. 메서드의 리턴 타입을 선언할 때 `List` 타입으로 선언하는 것과 `ArrayList` 타입으로 선언하는 것은 어떤 차이점이 있고 어떤 것을 선택하는 것이 좋을까요?

메서드의 리턴 타입의 경우도 마찬가지로 
`List` 타입으로 선언했을 경우 `ArrayList`, `LinkedList` 등, 반환된 데이터를 용도에 따라 다른 타입의 List에 사용하는 것이 가능하지만
`ArrayList`타입으로 반환하는 경우에는 `ArrayList`에서만 사용될 수 있다는 차이가 있습니다.
따라서, 유연성에서 이점이 있기 때문에 리턴 타입을 `List`타입으로 선언하는 것이 더 좋다고 생각됩니다.


> 3. `ArrayList` 는 불변리스트가 아니기 때문에, 리턴된 리스트에는 데이터의 삽입, 삭제, 변경이 일어날 수 있습니다. 리턴된 리스트에 변경이 일어날 수 있다면 어떤 일이 발생할까요?

`ArrayList`로 반환된 리스트에서 데이터 삽입, 삭제 등의 변경이 일어날 경우, 해당 데이터를 활용하는 메서드 등에서 변경된 데이터로 인해 의도와는 다른 결과를 보여주거나, 오류가 발생하는 등의 문제가 발생할 수 있습니다.

2024-02-01 04:02 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
> +            if (name.length() > 5) {
해당 숫자를 여러번 사용하게 된다면 상수로 사용했을 때, 코드 전체를 찾아서 해당 숫자를 수정하는 것이 아니라 상수 부분만 수정을 해주면 되기 때문에 유지보수성이 향상됩니다!
또한 상수의 의미를 알기 쉽게 정의한다면 의미 전달이나, 가독성 또한 향상됩니다!

2024-02-01 04:08 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
> +    public static int inputNumber() {
`inputName -> readName`
`inputNumber -> readNumber`
메서드 이름 위와 같이 수정해보았습니다!

혹시 이것보다 더 좋은 네이밍 방법이 있을까요?

2024-02-01 04:10 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
> +        if (!isNumber(number) || Integer.parseInt(number) <= 0) {
```
    public static void checkNumber(String number) {
        if (!isNumber(number)) {
            if (Integer.parseInt(number) <= 0) {
                throw new IllegalArgumentException("1 이상의 수를 입력해 주세요.");
            }
            throw new IllegalArgumentException("숫자를 입력해 주세요.");
        }
    }
```

위와 같이 예외처리를 세분화 해보았습니다!

2024-02-01 04:12 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +            if (car.getMoveDistance() == highScore) {
```
    public boolean isWinner(int highScore){
        return this.moveDistance == highScore;
    }
```

조언해 주신대로 Car에 isWinner 메서드를 추가하여 수정했습니다!

2024-02-01 04:17 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
>      private static final ArrayList<Car> cars = new ArrayList<>();
final로 선언된 변수는 한 번 할당된 값이 변경될 수 없는 특징을 가지고 있습니다.

또한 해당 코드처럼 static final로 선언된다면 모든 인스턴스에서 같은 값을 공유하는 상수가 되며, 
그냥 final로 선언된 변수는 인스턴스마다 각각의 다른 값을 가진 고유한 상수가 됩니다!

위 처럼 `ArrayList`를 final로 선언하게 된다면 최초에 참조한 `ArrayList` 외에 다른 `ArrayList`를 참조할 수 없게됩니다!

2024-02-01 04:18 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +        ArrayList<String> nameList = new ArrayList<>(Arrays.asList(names.split(",")));
굉장히 꼼꼼히 알아보셨네요 👍🏻👍🏻👍🏻👍🏻 너무 좋습니다!!
3번에서 말씀해주신 것처럼, 데이터가 변경되는 경우 의도와 다른 동작을 할 수 있게 됩니다. 
그렇기 때문에 추후 변경이 필요한 데이터가 아닌 경우, 리턴되는 리스트 (혹은 컬렉션 객체) 는 불변 객체로 리턴하는 것이 좋습니다 😄

2024-02-01 04:20 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +    public static int inputNumber() {
적합한 네이밍처럼 보입니다 👍🏻

2024-02-01 04:23 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
>      }
static과 final 선언의 특징을 다시 한 번 생각하며 보니, 코드가 잘못되었다는 것이 바로 이해 되었습니다!
```
    public static void runRace() {
        Output.resultMessage();
        for (int i = 0; i < raceCount; i++) {
            runRaceOneTime();
            Output.result(cars);
        }
    }

    public static void runRaceOneTime() {
        for (Car car : cars) {
            car.move();
        }
    }
```

위와 같이 재할당이나 리턴을 하지 않아도 기능을 수행하도록 수정했습니다!

2024-02-01 04:29 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      private static final ArrayList<Car> cars = new ArrayList<>();
맞습니다! 변수를 static final 로 선언하면 모든 인스턴스에서 공유할 수 있는 값이 됩니다 🙂
다만 조금 유의하셔야 하는 부분이 있어요. [구글 컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) 에서는 `ArrayList` 와 같이 내부 값이 변경될 수 있는 객체들을 상수로 지칭하고 있지 않습니다. 즉, 선언해주신 `cars` 는 좁은 의미에서는 상수가 아니라는 뜻입니다! 상수의 정의는 쉽게 혼동될 수 있으니 이 부분은 참고해주시면 좋을 것 같아요 😄

저는 유빈님이 `cars` 를 static 변수로 선언한 이유가 궁금한데요, static 변수로 하신 게 틀렸다는 말이 아닙니다 😅 유빈님께서 이런 구조로 설계한 이유가 궁금한 것이니 편하게 의견 남겨주세요!

2024-02-01 04:30 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      }
빠르게 캐치하시고 개선해주셨네요! 훌륭합니다 👍🏻

2024-02-01 04:32 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
> +        if (!isNumber(number) || Integer.parseInt(number) <= 0) {
```
    public static void checkNumber(String number) {
        if (!isNumber(number)) {
            throw new IllegalArgumentException("숫자를 입력해 주세요.");
        } else {
            if (Integer.parseInt(number) <= 0) {
                throw new IllegalArgumentException("1 이상의 수를 입력해 주세요.");
            }
        }
    }
```

위와 같이 예외처리를 세분화 해보았습니다!

2024-02-01 04:42 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
>      private static int raceCount;
인스턴드 필드는 해당 클래스의 인스턴스가 생성되었을 때, 필드는 각 인스턴스 마다 다른 고유한 값을 가질 수 있지만, static 필드의 경우, 인스턴스가 생성되어도 필드가 고유한 값을 가지는게 아니라 모두 같은 값을 가지게 된다는 차이가 있습니다.

static으로 선언하는 것과 그렇지 않은 것의 기능적인 차이를 완전히 이해하고 구현한 것은 아니지만,
필드를 static으로 선언한 이유는 RacingGameManager의 인스턴스를 생성하지 않아도 해당 필드를 사용할 수 있도록 하기 위해서 static으로 선언했습니다.

2024-02-01 04:57 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
>      public static void startRace() {
필드 선언과 마찬가지로 static으로 선언하는 것과 그렇지 않은 것의 기능적인 차이를 완전히 이해하고 구현한 것이 아니라, RacingGameManager의 인스턴스를 생성하지 않고 해당 클래스의 메서드를 사용하기 위해서 위와 같이 메서드를 static으로 구현했습니다.

하지만 추후 기능 추가, 변경 등을 고려한다면 다형성을 고려해 static 메서드로 선언하는 것이 아니라 인스턴스 메서드로 선언하는 것이 좋을 것 같다고 생각이 됩니다!

2024-02-01 04:58 UTC, leeshin20 commented on src/main/java/racingcar/Application.java
> +}
설정 참고 하겠습니다 감사합니다!

2024-02-01 06:42 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +        Output.inputNameMessage();
확실히 말씀해주신 registerCar가 더 적합한 표현 같습니다!

감사합니다!!

2024-02-01 07:45 UTC, leeshin20 commented on src/main/java/racingcar/Car.java
> +    private static final int FORWARD_CONSTANT = 4;
말씀 주신 부분의 변수, 메서드명 다시 한 번 수정했습니다!
영어를 잘 못 하기 때문에 섣불리 변수명을 짓기 보다, 저도 이름 짓기 전에 사전으로 단어의 뜻을 한 번 찾아보는 습관을 가져보도록 하겠습니다!

현재 상황뿐만 아니라 추후에 추가되거나 변경될 수 있는 점을 생각하여 매직넘버를 상수로 추출할 것! 기억하겠습니다!

2024-02-01 07:47 UTC, leeshin20 commented on src/test/java/racingcar/InputTest.java
> +    void 자동차_이름_분할_테스트() {
궁금했던 부분이었는데 너무 자세하게 잘 써주셔서 감사합니다! 한번에 이해가 잘 됐습니다~

2024-02-01 08:37 UTC, leeshin20 commented on src/main/java/racingcar/Car.java
> +    }
move 메서드 안에 있던 두개의 기능을 다음과 같이 분리했습니다.
```
    public void move(int number) {
        if (number >= FORWARD_THRESHOLD) {
            distance += 1;
        }
    }

    public int pickNumber() {
        return Randoms.pickNumberInRange(0, 9);
    }
```
기능을 분리함으로써 move메서드의 기능을 테스트할 때, 4 이상의 수가 랜덤으로 나올때 까지 반복하는 것이 아니라, 원하는 수를 지정하여 명확하게 테스트를 진행할 수 있도록 변경했습니다.

```
@Test
    void carMoveTest() {
        Car testCar = new Car("test");
        testCar.move(FORWARD_THRESHOLD);
        assertThat(testCar.getMoveDistance()).isEqualTo(1);
    }
```
여러대의 자동차의 이동 여부도 다음과 같이 테스트 코드를 수정해 보았습니다.
```
@Test
    void 경주_진행시_자동차_이동_테스트() {
        ArrayList<Car> cars = new ArrayList<>();
        for(int i=0; i<10; i++) {
            cars.add(new Car("test"));
            cars.get(i).move(FORWARD_THRESHOLD);
            assertThat(cars.get(i).getMoveDistance()).isEqualTo(1);
        }
    }
```
이런 방법이 아닌, 기존 move 메서드의 기능을 나누지 않고 해결할 수 있는 방법이 혹시 있는지 궁금합니다!

2024-02-01 08:56 UTC, leeshin20 commented on src/main/java/racingcar/Output.java
> +public class Output {
유틸성 클래스는 모든 클래스에서 동일하게 수행되는 기능들을 모아놓은 클래스입니다. 따라서 해당 클래스의 필드나 메서드가 변경될 필요가 없기 때문에 인스턴스를 만들어서 사용할 필요가 없습니다.

만약 이런 유틸 클래스의 인스턴스를 만들어서 사용한다면 실행되는 기능 자체에는 변화가 없겠지만, 불필요한 인스턴스가 생성됨으로써 메모리자원이 낭비될 수 있으며, 다른 개발자가 유틸 클래스의 인스턴스가 생성된 것을 본다면 해당 클래스가 일반적인 클래스인지, 유틸성 클래스인지 알아보기 어려울 수 있게 된다는 차이점이 존재할 것 같습니다!

2024-02-05 05:18 UTC, Cyma-s requested changes
안녕하세요 유빈님! 리뷰가 늦어 죄송합니다 ㅠㅠ 제가 이전 리뷰에 답글만 달고 새롭게 리뷰를 다는 것을 잊고 있었어요. 다시 한 번 죄송합니다 🙇‍♀️
랜덤한 값을 테스트하는 로직이 매우 간결해졌더라고요 👍🏻 코드가 점점 좋아지고 있습니다!!
소소하게 컨벤션을 고치는 리뷰와 유빈님의 의견이 궁금했던 부분 위주로 리뷰 남겨보았습니다.
이번 리뷰도 파이팅입니다 🚀

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/Car.java
> +    private static final int FORWARD_THRESHOLD = 4;
[오라클 컨벤션 가이드](https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html) 에 의하면 static 변수는 instance 변수 위에 위치해야 합니다 !

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +        ArrayList<String> splitNames = new ArrayList<>(Arrays.asList(names.split(",")));
유빈님이 이전 리뷰에 답글을 남겨주신 것처럼 확장성과 유연성 측면에서 상위 타입으로 선언하는 것이 좋습니다!

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
>      public static ArrayList<String> splitName(String names) {
마찬가지로 매개변수도 상위 타입으로 선언해주세요!

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
>      public static void checkName(ArrayList<String> nameList) {
매개변수의 이름에도 타입이 들어가는 것은 추후 변경이 일어났을 때 관리 포인트가 늘어날 수 있다는 단점이 있습니다 🥲

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
>          }
throw 를 하면 자동으로 아래 코드가 실행되지 않기 때문에 다음과 같이 리팩토링 해볼 수 있을 것 같아요 :)

```suggestion
        if (!isNumber(number)) {
            throw new IllegalArgumentException("숫자를 입력해 주세요.");
        } 
        if (Integer.parseInt(number) <= 0) {
            throw new IllegalArgumentException("1 이상의 수를 입력해 주세요.");
        }
```

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      private static int raceCount;
맞아요. 그리고 `RacingGameManager` 가 다른 게임을 여러 개 실행해야 하는 경우 문제가 있을 수 있겠죠?
코드에 적용도 해주시면 좋을 것 같습니다 👍🏻

2024-02-05 05:18 UTC, Cyma-s commented on src/test/java/racingcar/CarTest.java
> +    private static final int FORWARD_THRESHOLD = 4;
변수와 메서드 사이는 공백으로 구분해주세요!

2024-02-05 05:18 UTC, Cyma-s commented on src/test/java/racingcar/RacingTest.java
> +            cars.get(i).move(FORWARD_THRESHOLD);
`move` 의 인자가 4 이하인 경우도 테스트하면 더 좋을 것 같아요 👍🏻

2024-02-05 05:18 UTC, Cyma-s commented on src/test/java/racingcar/RacingTest.java
> +        cars.get(1).move(FORWARD_THRESHOLD);
코드가 간략해졌네요 👍🏻👍🏻👍🏻

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>          int highScore = findHighScore(cars);
`findHighScore` 는 외부에서 쓰이지 않는 메서드이기 때문에, private 으로 선언해주는 것이 좋겠네요 🤔

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/Car.java
> +    }
랜덤한 숫자를 생성하는 역할이 `Car` 의 역할일까요? 유빈님의 의견이 궁금합니다 :)

2024-02-05 05:18 UTC, Cyma-s commented on src/main/java/racingcar/Car.java
> +        distance = 0;
위의 필드에 값을 할당할 때는 `this` 키워드를 적어주셨는데, 아래쪽에는`this` 키워드가 없네요.
코드를 작성할 때는 자신만의 규칙이 중요하기 때문에, 일관적으로 코드를 작성하는 것이 좋습니다.

2024-02-07 05:49 UTC, leeshin20 commented on src/main/java/racingcar/Car.java
> +        distance = 0;
`this.name`과 맞춰서 `distance -> this.distance` 로 수정하였습니다!

2024-02-07 05:53 UTC, leeshin20 commented on src/main/java/racingcar/Car.java
> +    }
`move` 메서드의 연장선으로 생각하고 Car에 `pickNumber` 메서드를 만들었는데
자동차의 이동 여부를 결정하는 것은 Car의 역할이 아니라
게임 진행을 담당하는 RacingGameManager의 역할이 맞다고 생각이 되었습니다.

`pickNumber` 메서드의 위치를 Car에서 RacingGameManager로 옮겼습니다!!

2024-02-07 05:56 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
>          int highScore = findHighScore(cars);
`private int findHighScore()`로 수정하였습니다!

외부에서 쓰이지 않는 메서드는 혼동을 방지하지 위해 private로 선언하기!

2024-02-07 05:58 UTC, leeshin20 commented on src/test/java/racingcar/RacingTest.java
> +            cars.get(i).move(FORWARD_THRESHOLD);
```
@Test
    void 경주_진행시_자동차_이동_테스트() {
        ArrayList<Car> cars = new ArrayList<>();
        for (int i = 0; i < 3; i++) {
            cars.add(new Car("test" + i));
            cars.get(i).move(FORWARD_THRESHOLD);
            assertThat(cars.get(i).getMoveDistance()).isEqualTo(1);
        }
        for (int i = 3; i < 6; i++) {
            cars.add(new Car("test" + i));
            cars.get(i).move(STOP_THRESHOLD);
            assertThat(cars.get(i).getMoveDistance()).isEqualTo(0);
        }
    }
```

위 코드처럼 전체 테스트 반복 횟수를 줄이고
차가 전진하지 않고, 멈춰있는 경우의 테스트 코드도 추가하였습니다!

2024-02-07 05:59 UTC, leeshin20 commented on src/test/java/racingcar/CarTest.java
> +    private static final int FORWARD_THRESHOLD = 4;
기본적인 컨벤션 지킬 수 있도록 꼼꼼하게 항상 살펴보겠습니다!

2024-02-07 06:00 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
>      public static void checkName(ArrayList<String> nameList) {
`nameList -> names`로 수정하였습니다!

변수, 메서드 등 이름을 지을 때, 이름에 타입이 포함되지 않도록 주의하겠습니다!

2024-02-07 06:03 UTC, leeshin20 commented on src/main/java/racingcar/Car.java
> +    private static final int FORWARD_THRESHOLD = 4;
상수를 새로 추가하면서 자연스레 기존에 있던 변수 아래에 선언한 것 같습니다.

변수를 새로 추가하거나, 기존 변수를 static으로 수정하는 과정에서도 컨벤션을 유지하도록 신경쓰겠습니다!

2024-02-07 06:04 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
> +        ArrayList<String> splitNames = new ArrayList<>(Arrays.asList(names.split(",")));
상위타입인 List타입으로 수정하였습니다!

2024-02-07 06:04 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
>      public static ArrayList<String> splitName(String names) {
마찬가지로 상위타입인 List타입으로 수정하였습니다!!

2024-02-07 06:06 UTC, leeshin20 commented on src/main/java/racingcar/Input.java
>          }
조언해 주신대로 리팩토링 해보았습니다!!

예외를 처리하는 부분이 익숙치 않다보니 해당 부분 진행할 때 앞으로 더욱 신경쓰겠습니다!

2024-02-07 06:13 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
>      private static int raceCount;
지적 감사합니다!!!
`RacingGameManager`가 한 가지의 게임만 실행하는 경우만 생각하고, 여러 개의 게임을 실행하는 경우는 생각하지 못 한 것 같습니다!!

여러 개의 게임이 실행되는 경우라면, `cars`와 `raceCount`가 게임마다 다른 값을 가지고 있어야 되는데, static으로 선언하면 모든 인스턴스가 같은 값을 공유하기 때문에 이런 문제를 방지하기 위해

static으로 선언하지 않고, RacingGameManger의 인스턴스를 생성하여 사용하도록 수정하였습니다!

2024-02-08 11:35 UTC, Cyma-s commented on src/main/java/racingcar/Car.java
> +    }
기능을 나누어야 `Random` 을 분리할 수 있기 때문에 유빈님이 해주신 방법이 맞습니다 ☺️

2024-02-08 11:36 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
>      private static int raceCount;
여러 개의 게임이 실행되는 경우 어떤 부분이 문제가 될 지 잘 알아봐주셨네요 👍🏻👍🏻👍🏻

2024-02-08 11:51 UTC, Cyma-s requested changes
안녕하세요 유빈님~ 리뷰 반영하시느라 고생 많으셨습니다 👍🏻
그런데 아직 코드에서 이전 리뷰가 반영되지 않은 부분들이 조금 있어서 마지막 Request Change 드립니다!!
새해 복 많이 받으시고, 연휴 잘 보내세요 ☺️

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/Application.java
>          // TODO: 프로그램 구현
구현이 완료된 TODO 주석은 삭제해주세요 :)
참고로 삭제되지 않은 TODO 주석은 IDE 에서 지속적으로 경고를 띄워준답니다 👍

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/Application.java
> +        RacingGameManager race = new RacingGameManager();
`RacingGameManager` 의 인스턴스 이름이 `race` 로 줄어든 이유가 있을까요?

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +    public static List<String> readName() {
상위 타입으로 변경 👍🏻

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/Input.java
> +    public static void checkName(List<String> names) {
적절한 매개변수 이름 👍🏻👍🏻👍🏻

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +    private final ArrayList<Car> cars = new ArrayList<>();
이 부분도 상위 타입으로 바꿔주시면 좋을 것 같아요 !

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +    public void registerCar() {
이제보니 해당 메서드에서는 여러 개의 Car 를 등록하는 과정을 거치고 있기 때문에, `registerCars` 가 더 적합한 네이밍일 것 같습니다.

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +        return Randoms.pickNumberInRange(0, 9);
이 부분도 상수로 관리하면 더 좋지 않을까요?

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +    public int pickNumber() {
메서드 이름에서도 랜덤하게 숫자를 고른다는 의미가 들어갔으면 좋겠어요 :)

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +    public ArrayList<String> findWinner(ArrayList<Car> cars) {
여기는 아직 수정이 안 된 것 같아요!!

2024-02-08 11:51 UTC, Cyma-s commented on src/main/java/racingcar/RacingGameManager.java
> +    private int findHighScore(ArrayList<Car> cars) {
중복되는 리뷰는 최대한 안 남기려고 노력하고 있어요. 혹시 리뷰로 언급되지 않았던 부분이더라도 꼼꼼히 확인해주세요 🙂

2024-02-08 11:51 UTC, Cyma-s commented on src/test/java/racingcar/RacingTest.java
> +        for (int i = 0; i < 3; i++) {
한 메서드를 3번 테스트하시는 이유가 있으실까요?

2024-02-08 11:51 UTC, Cyma-s commented on src/test/java/racingcar/RacingTest.java
> +        }
다른 케이스의 테스트도 작성해주셨네요 👍🏻
다만 메서드가 하나의 책임을 갖는 것처럼 테스트 코드의 메서드들도 하나의 케이스씩만 테스트하는 것이 관리하기에 편할 것 같네요.

2024-02-14 06:40 UTC, leeshin20 commented on src/main/java/racingcar/Application.java
>          // TODO: 프로그램 구현
TODO 주석은 IDE에서 일반적인 주석과는 다르게 취급이 되는 것이네요!
삭제했습니다!

2024-02-14 06:41 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +    private final ArrayList<Car> cars = new ArrayList<>();
수정했습니다!

2024-02-14 06:41 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +    public ArrayList<String> findWinner(ArrayList<Car> cars) {
수정했습니다!

2024-02-14 06:43 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +    public int pickNumber() {
_랜덤_ 이라는 것을 알리기 위해 `pickRandomNumber()`로 메서드 이름을 수정했습니다!

2024-02-14 06:46 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +        return Randoms.pickNumberInRange(0, 9);
```
0(시작) -> MIN_RANDOM_NUMBER
9(끝) -> MAX_RANDOM_NUMBER
```
위와 같이 랜덤 메서드의 숫자 범위를
상수로 관리하도록 수정했습니다!

2024-02-14 06:48 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +    public void registerCar() {
수정했습니다!

작은 차이로 전달되는 의미가 달라질 수 있으니 더욱 네이밍에 신경 쓰도록 하겠습니다!

2024-02-14 06:55 UTC, leeshin20 commented on src/main/java/racingcar/RacingGameManager.java
> +    private int findHighScore(ArrayList<Car> cars) {
수정하면 안될 부분까지 건드릴까 우려되어 리뷰에서 인용해주신 부분만 수정을 했는데, 앞으로는 스스로 판단하여 공통적으로 적용될 것 같은 부분들은 남겨주신 피드백을 반영하도록 하겠습니다!
여러 번 같은 내용 확인하게 하여 번거롭게 해서 죄송합니다🥲

2024-02-14 06:57 UTC, leeshin20 commented on src/test/java/racingcar/RacingTest.java
> +        }
확실히 말씀주신 메서드의 경우처럼 테스트 코드의 경우도 하나의 테스트가 하나의 역할만 하는 것이 맞다는 생각이 듭니다!
해당 부분 테스트 코드를 분리하여 수정했습니다!

2024-02-14 07:02 UTC, leeshin20 commented on src/test/java/racingcar/RacingTest.java
> +        for (int i = 0; i < 3; i++) {
경주가 진행되면 이동이 한번이 아닌 여러 번 발생하는 경우가 있을 것이기 때문에 3회 정도 이동 시켜보는 게 어떨까 하여 위와 같이 테스트 코드를 작성한 것 같습니다!
굳이 메서드를 여러 번 테스트할 필요 없이 한번만 해도 충분한 걸까요?

2024-02-14 07:25 UTC, leeshin20 commented on src/main/java/racingcar/Application.java
> +        RacingGameManager race = new RacingGameManager();
`RacingGameManager`가 관리할 `race` 라고 생각하여 인스턴스의 이름을 `race`로 지었습니다.

인스턴스의 이름을 `raceManager`, `firstRaceManager`같은 식으로 변경하는 것이 좋을 것 같다는 생각이 듭니다.

혹은 단순 인스턴스 이름 변경이 아닌 `RacingGameManager`의 기능을

`RacingGame` - 자동차 경주
`RacingGameManager` - 자동차 경주를 관리

위와 같이 두 개의 클래스로 분리하는 것이 더 좋은 방법일지 궁금합니다.

2024-02-16 10:56 UTC, Cyma-s commented on src/test/java/racingcar/RacingTest.java
> +        for (int i = 0; i < 3; i++) {
조건을 완전하게 통제할 수 있다면 동일한 메서드를 여러 번 호출한 경우에도 동일한 결과를 얻을 수 있다고 생각할 수 있습니다!

2024-02-16 23:27 UTC, Cyma-s commented on src/main/java/racingcar/Application.java
> +        RacingGameManager race = new RacingGameManager();
각각의 클래스의 책임을 명확하게 나누고, 분리함으로써 확장성이 높아진다고 생각하시면 클래스를 분리하셔도 좋습니다! 👍🏻

2024-02-16 23:29 UTC, Cyma-s approved these changes
안녕하세요 유빈님 :) 마지막 리뷰 잘 반영해주셨네요! 👍🏻 반영하시느라 고생 많으셨습니다 😄
자동차 경주 미션은 주어진 요구사항을 충분히 만족시켰다고 생각해서, 여기서 Approve 하겠습니다!
수고 많으셨습니다 🚀

2024-03-22 13:10 UTC, merged